//Auth 
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const CLEAR_AUTH = 'SET_AUTH';
export const AUTH_REQUEST = 'AUTH_REQUESTD';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

//User
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_ERROR = 'USER_INFO_ERROR';
export const USER_REQUEST = 'USER_REQUEST';
export const REQUEST_CHALLENGE_SUCCESS = 'REQUEST_CHALLENGE';
export const FETCH_CHALLENGE_INFO_SUCCESS = 'FETCH_CHALLENGE_INFO_SUCCESS';
export const ADD_CHALLENGE_SUCCESS = 'ADD_CHALLENGE_SUCCESS';


//Challenges
export const CHALLENGE_SUCCESS = 'FETCH_CHALLENGE_SUCCESS';
export const CHALLENGE_ERROR = 'FETCH_CHALLENGE_ERROR';
export const CHALLENGE_REQUEST = 'FETCH_CHALLENGE_REQUEST';
export const ACTIVATE_CHALLENGE_SUCCESS = 'ACTIVATE_CHALLENGE_SUCCESS';

//Team
export const TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS';
export const TEAM_ERROR = 'FETCH_TEAM_ERROR';
export const TEAM_REQUEST = 'FETCH_TEAM_REQUEST';
export const ADD_MEMBER_A = 'ADD_MEMBER_A';
export const ADD_MEMBER_B = 'ADD_MEMBER_B';

//Proof
export const PROOF_SUCCESSA = 'PROOF_SUCCESSA';
export const PROOF_SUCCESSB = 'PROOF_SUCCESSB';
export const PROOF_ERROR = 'PROOF_ERROR';
export const PROOF_REQUEST = 'PROOF_REQUEST';
export const UPLOAD_PROOF_SUCCESS = 'UPLOAD_PROOF_SUCCESS';
export const CHALLENGE_PROOF_SUCCESS = 'CHALLENGE_PROOF_SUCCESS';

//Global Data
export const ALL_CHALLENGES_SUCCESS = 'ALL_CHALLENGES_SUCCESS';
export const ALL_CHALLENGES_ERROR = 'ALL_CHALLENGES_ERROR';
export const ALL_CHALLENGES_REQUEST = 'ALL_CHALLENGES_REQUEST'

//Admin 
export const ADMIN_SUCCESS = 'ADMIN_SUCCESS';
export const ADMIN_ERROR = 'ADMIN_ERROR';
export const ADMIN_REQUEST = 'ADMIN_REQUEST';
export const ACCEPT_USER_SUCCESS = 'ACCEPT_USER_SUCCESS';
export const REJECT_USER_SUCCESS = 'REJECT_USER_SUCCESS';






//Leaderboard
export const FETCH_LEADERBOARD_SUCCESS = 'FETCH_LEADERBOARD_SUCCESS';
export const FETCH_LEADERBOARD_ERROR= 'FETCH_LEADERBOARD_ERROR';


//User
export const ACCEPT_PROOF = 'ACCEPT_PROOF';
export const REJECT_PROOF = 'REJECT_PROOF';
export const CHALLENGE_PROOF = 'CHALLENGE_PROOF';

//Chat
