//Leaderboard
export const FETCH_LEADERBOARD_SUCCESS = 'FETCH_LEADERBOARD_SUCCESS';
export const FETCH_LEADERBOARD_ERROR= 'FETCH_LEADERBOARD_ERROR';

//Challenges
export const FETCH_CHALLENGE_SUCCESS = 'FETCH_CHALLENGE_SUCCESS';
export const FETCH_CHALLENGES_SUCCESS = 'FETCH_CHALLENGES_SUCCESS';
export const FETCH_CHALLENGE_ACTIVE = 'FETCH_CHALLENGE_ACTIVE ';
export const FETCH_CHALLENGE_COMPLETE = 'FETCH_CHALLENGES_COMPLETE';
export const FETCH_PROOF_CHALLENGED = 'FETCH_PROOF_CHALLENGED';
export const ADD_CHALLENGE = 'ADD_CHALLENGE';

//Team
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS';

//User
export const FETCH_USER_INFO_SUCCESS = 'FETCH_ADMIN_SUCCESS';
export const FETCH_CHALLENGE_ID_SUCCESS = 'FETCH_CHALLENGE_ID_SUCCESS';
export const FETCH_CHALLENGE_REQUEST = 'FETCH_CHALLENGE_REQUEST';
export const FETCH_CHALLENGE_REQUEST_STATUS = 'FETCH_CHALLENGE_REQUEST_STATUS';
export const FETCH_USER_SCORE = 'FETCH_USER_SCORE';
export const ACCEPT_USER = 'ACCEPT_USER';
export const REJECT_USER = 'REJECT_USER';
export const REQUEST_CHALLENGE = 'REQUEST_CHALLENGE';
export const REQUEST_ACCEPTED = 'REQUEST_ACCEPTED';
export const REQUEST_REJECTED = 'REQUEST_REJECTED';
export const ACCEPT_PROOF = 'ACCEPT_PROOF';
export const REJECT_PROOF = 'REJECT_PROOF';
export const CHALLENGE_PROOF = 'CHALLENGE_PROOF';

//Chat

//Friend's List